In [1]:
sizes = [2,3,4]

In [2]:
for x, y in zip(sizes[:-1], sizes[1:]):
    print(x, y)

2 3
3 4


In [3]:
len(sizes)

3

In [4]:
import numpy as np
a = np.array([1,2,3])
1 - a

array([ 0, -1, -2])

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
x = zip(a,b)
for i,(a,b) in enumerate(x):
    print(i,a,b)

0 1 4
1 2 5
2 3 6


In [6]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[1],[2], [3]])
z = np.dot(x,y)

In [7]:
a = [1,2,3]
b = [4,5,6]
x = zip(a,b)

In [8]:
z.shape

(2, 1)

In [9]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x.mean(axis=1)

array([2., 5., 8.])

In [10]:
import numpy as np
import gzip
import os
import urllib.request

# 1. Hàm tải dữ liệu (nếu chưa có)
def download_mnist(save_dir='./data'):
    base_url = "https://storage.googleapis.com/cvdf-datasets/mnist/"
    files = [
        "train-images-idx3-ubyte.gz", "train-labels-idx1-ubyte.gz",
        "t10k-images-idx3-ubyte.gz", "t10k-labels-idx1-ubyte.gz"
    ]

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    for file in files:
        path = os.path.join(save_dir, file)
        if not os.path.exists(path):
            print(f"Đang tải {file}...")
            urllib.request.urlretrieve(base_url + file, path)
    print("Đã tải xong dữ liệu!")

# 2. Hàm đọc file Images
def load_images(filename):
    with gzip.open(filename, 'rb') as f:
        # Bỏ qua 16 byte đầu (header info: magic number, number of images, rows, cols)
        data = np.frombuffer(f.read(), np.uint8, offset=16)
    # Reshape thành (số lượng ảnh, 784) - Flatten luôn để đưa vào mạng NN
    return data.reshape(-1, 784)

# 3. Hàm đọc file Labels
def load_labels(filename):
    with gzip.open(filename, 'rb') as f:
        # Bỏ qua 8 byte đầu (header info)
        data = np.frombuffer(f.read(), np.uint8, offset=8)
    return data

# --- CHẠY ---
download_mnist()

X_train = load_images('./data/train-images-idx3-ubyte.gz')
y_train = load_labels('./data/train-labels-idx1-ubyte.gz')
X_test = load_images('./data/t10k-images-idx3-ubyte.gz')
y_test = load_labels('./data/t10k-labels-idx1-ubyte.gz')

print(f"X_train shape: {X_train.shape}") # (60000, 784)
print(f"y_train shape: {y_train.shape}") # (60000,)

Đã tải xong dữ liệu!
X_train shape: (60000, 784)
y_train shape: (60000,)


In [11]:
from Network import Network
network = Network([784,64,16,10], batch_size=32, lr=0.01)

3


In [12]:
onehot_matrix = np.zeros((y_train.size, 10))
onehot_matrix.shape

(60000, 10)

In [13]:
onehot_matrix[np.arange(y_train.size), y_train] = 1
onehot_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(60000, 10))

In [16]:
y_train = onehot_matrix
y_train.shape

(60000, 10)

In [15]:
network.train(X_train, y_train)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0.

/home/nutcracker/PycharmProjects/dudl/Network.py:7: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-z))


i:  1
delta:  (16, 32)
next_w_transpose:  (64, 16)
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.