In [1]:
sizes = [2,3,4]

In [2]:
for x, y in zip(sizes[:-1], sizes[1:]):
    print(x, y)

2 3
3 4


In [3]:
len(sizes)

3

In [4]:
import numpy as np
a = np.array([1,2,3])
1 - a

array([ 0, -1, -2])

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
x = zip(a,b)
for i,(a,b) in enumerate(x):
    print(i,a,b)

0 1 4
1 2 5
2 3 6


In [6]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[1],[2], [3]])
z = np.dot(x,y)

In [7]:
a = [1,2,3]
b = [4,5,6]
x = zip(a,b)

In [8]:
z.shape

(2, 1)

In [9]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x.mean(axis=1)

array([2., 5., 8.])

In [10]:
import numpy as np
import gzip
import os
import urllib.request

# 1. Hàm tải dữ liệu (nếu chưa có)
def download_mnist(save_dir='./data'):
    base_url = "https://storage.googleapis.com/cvdf-datasets/mnist/"
    files = [
        "train-images-idx3-ubyte.gz", "train-labels-idx1-ubyte.gz",
        "t10k-images-idx3-ubyte.gz", "t10k-labels-idx1-ubyte.gz"
    ]

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    for file in files:
        path = os.path.join(save_dir, file)
        if not os.path.exists(path):
            print(f"Đang tải {file}...")
            urllib.request.urlretrieve(base_url + file, path)
    print("Đã tải xong dữ liệu!")

# 2. Hàm đọc file Images
def load_images(filename):
    with gzip.open(filename, 'rb') as f:
        # Bỏ qua 16 byte đầu (header info: magic number, number of images, rows, cols)
        data = np.frombuffer(f.read(), np.uint8, offset=16)
    # Reshape thành (số lượng ảnh, 784) - Flatten luôn để đưa vào mạng NN
    return data.reshape(-1, 784)

# 3. Hàm đọc file Labels
def load_labels(filename):
    with gzip.open(filename, 'rb') as f:
        # Bỏ qua 8 byte đầu (header info)
        data = np.frombuffer(f.read(), np.uint8, offset=8)
    return data

# --- CHẠY ---
download_mnist()

X_train = load_images('./data/train-images-idx3-ubyte.gz')
y_train = load_labels('./data/train-labels-idx1-ubyte.gz')
X_test = load_images('./data/t10k-images-idx3-ubyte.gz')
y_test = load_labels('./data/t10k-labels-idx1-ubyte.gz')

print(f"X_train shape: {X_train.shape}") # (60000, 784)
print(f"y_train shape: {y_train.shape}") # (60000,)

Đã tải xong dữ liệu!
X_train shape: (60000, 784)
y_train shape: (60000,)


In [11]:
from PIL import  Image
Image.fromarray(X_train).show()

In [12]:
from Network import Network
network = Network([784,32,10], batch_size=32, lr=0.1, epochs=100)

2
(10, 1)


In [13]:
onehot_matrix = np.zeros((y_train.size, 10))
onehot_matrix.shape

(60000, 10)

In [14]:
onehot_matrix[np.arange(y_train.size), y_train] = 1


In [15]:
y_train = onehot_matrix
y_train.shape

(60000, 10)

In [16]:
X_train = X_train/255.0

In [17]:
# network.train(X_train, y_train)

In [18]:
_, active_list = network.forward(X_train[-2:])

In [19]:
active_list[-1]

array([[0.40744539, 0.40750939],
       [0.26891206, 0.2682582 ],
       [0.75509562, 0.75503561],
       [0.35755018, 0.35832316],
       [0.59431405, 0.59562536],
       [0.35589342, 0.35500189],
       [0.19579164, 0.19644521],
       [0.66919982, 0.66843946],
       [0.77677387, 0.77700791],
       [0.27831712, 0.27680361]])

In [20]:
active_list[-1].shape

(10, 2)

In [21]:
np.argmax(active_list[-1])

np.int64(17)

In [22]:
y.ndim

2

In [23]:
y_train[-1].shape

(10,)

In [24]:
y_train.shape

(60000, 10)

In [25]:
x = [1,2,3,4,3,2,1]
np.argmax([x])

np.int64(3)

In [26]:
y_train[-2:]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [27]:
X_train.shape

(60000, 784)

In [30]:
np.mean(X_train, axis=0)

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       8.23529412e-06, 3.07189542e-05, 1.41176471e-05, 5.88235294e-07,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.04575163e-06, 3.59477124e-06, 3.64052288e-05, 9.52287582e-05,
       1.71437908e-04, 2.51372549e-04, 4.71111111e-04, 6.30326797e-04,
       6.83071895e-04, 6.95816993e-04, 7.42418301e-04, 6.82941176e-04,
       7.33071895e-04, 6.02549020e-04, 3.92614379e-04, 2.79346405e-04,
       2.11045752e-04, 8.37908497e-05, 3.95424837e-05, 1.38562092e-05,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      